// <auto-generated />
using System;
using FutureMe.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FutureMe.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240125215116_mig")]
    partial class mig
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FutureMe.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("LetterId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LetterId");

                    b.HasIndex("UserId");

                    b.ToTable("comments");
                });

            modelBuilder.Entity("FutureMe.Models.Letter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("bit");

                    b.Property<DateTime>("SendingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("WritingDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("letters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Dear future me, I hope you are doing well and have achieved your goals. I am writing this letter to remind you of the things that matter to you and to encourage you to keep going. Remember to be grateful for what you have, to be kind to yourself and others, and to enjoy the present moment. You have come a long way and I am proud of you. Love, your past self.",
                            Email = "user1@example.com",
                            IsPublic = true,
                            SendingDate = new DateTime(2024, 12, 9, 12, 1, 23, 0, DateTimeKind.Local),
                            Title = "A letter to myself",
                            UserId = 0,
                            WritingDate = new DateTime(2023, 12, 9, 12, 1, 23, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 2,
                            Content = "Hello future me, I am writing this letter to tell you that you are awesome and that you can do anything you set your mind to. I know you have faced many challenges and overcome many obstacles, but you never gave up. You are strong, resilient, and courageous. I want you to remember that you are not alone, that you have people who love you and support you. I also want you to have fun and enjoy life, because you deserve it. You are amazing and I love you. Sincerely, your past self.",
                            Email = "user2@example.com",
                            IsPublic = false,
                            SendingDate = new DateTime(2025, 12, 9, 12, 1, 23, 0, DateTimeKind.Local),
                            Title = "A letter to myself",
                            UserId = 0,
                            WritingDate = new DateTime(2023, 12, 9, 12, 1, 23, 0, DateTimeKind.Local)
                        });
                });

            modelBuilder.Entity("FutureMe.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PhoneNumber")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("users");
                });

            modelBuilder.Entity("FutureMe.Models.Comment", b =>
                {
                    b.HasOne("FutureMe.Models.Letter", "Letter")
                        .WithMany("Comments")
                        .HasForeignKey("LetterId");

                    b.HasOne("FutureMe.Models.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId");

                    b.Navigation("Letter");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FutureMe.Models.Letter", b =>
                {
                    b.HasOne("FutureMe.Models.User", "User")
                        .WithMany("Letters")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FutureMe.Models.Letter", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("FutureMe.Models.User", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Letters");
                });
#pragma warning restore 612, 618
        }
    }
}
